// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzHWStbgsyFJPURJ59MqxXUUoGHhza1Y',
    appId: '1:1070734876720:android:d5fd53949ccd0f31ba8df5',
    messagingSenderId: '1070734876720',
    projectId: 'expried-app',
    storageBucket: 'expried-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2oHwPqn8WGXf1bMP7fh_YLJTPlUrrpI',
    appId: '1:1070734876720:ios:7a551ab95223c232ba8df5',
    messagingSenderId: '1070734876720',
    projectId: 'expried-app',
    storageBucket: 'expried-app.appspot.com',
    androidClientId: '1070734876720-18dpmarol6g4cjfa5q6gp983j0t2sh4t.apps.googleusercontent.com',
    iosClientId: '1070734876720-2d966tkshefr19tcnu24fmult1110o0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.expriedItemApp',
  );
}
